import { useEffect, useState } from 'react'
import type { ReactNode } from 'react'
import {
  Alert, Button, Card, Col, Form, Input, InputNumber, Row, Select, Space, Statistic,
  Table, Tag, Typography, message,
} from 'antd'
import type { TableColumnsType } from 'antd'
import {
  ApartmentOutlined, InboxOutlined, RobotOutlined, SendOutlined,
  ShoppingCartOutlined, UserOutlined,
} from '@ant-design/icons'
import { api, getErrorMessage } from './api'

const { Title, Text, Paragraph } = Typography

function HeaderBlock({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) {
  return <div className="hero-row"><div><Text className="eyebrow">{eyebrow}</Text><Title>{title}</Title><Paragraph>{description}</Paragraph></div></div>
}

function DataLoading({ children, loading }: { children: ReactNode; loading: boolean }) {
  return loading ? <div className="table-loading">載入資料中…</div> : children
}

export function InventoryWorkspace() {
  const [items, setItems] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [moveForm] = Form.useForm()
  const load = async () => { setLoading(true); try { setItems((await api.get('/data/inventory')).data.items || []) } catch (e) { message.error(getErrorMessage(e)) } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  const move = async (values: Record<string, unknown>) => { try { await api.post('/data/inventory/moves', values); message.success('庫存異動已寫入'); moveForm.resetFields(); await load() } catch (e) { message.error(getErrorMessage(e)) } }
  const low = items.filter((item) => Number(item.stock || 0) <= Number(item.reorder_point || 0))
  const columns: TableColumnsType<any> = [
    { title: '商品', dataIndex: 'name', render: (v, row) => <div><b>{v}</b><small className="cell-secondary">{row.product_id}</small></div> },
    { title: '目前庫存', dataIndex: 'stock', render: (v) => <b>{v ?? 0}</b> },
    { title: '安全庫存', dataIndex: 'reorder_point' }, { title: '日均銷量', dataIndex: 'daily_sales' },
    { title: '狀態', render: (_, row) => Number(row.stock || 0) <= Number(row.reorder_point || 0) ? <Tag color="red">需要補貨</Tag> : <Tag color="green">正常</Tag> },
  ]
  return <><HeaderBlock eyebrow="ERP / INVENTORY OPERATIONS" title="庫存證據與異動" description="庫存查詢與入庫／出庫共用同一個交易邊界，異動會留下 stock_moves 紀錄。" /><Row gutter={[16, 16]} className="stat-row"><Col xs={24} md={8}><Card className="stat-card stat-blue" bordered={false}><Statistic title="商品 SKU 數" value={items.length} prefix={<InboxOutlined />} /></Card></Col><Col xs={24} md={8}><Card className="stat-card stat-orange" bordered={false}><Statistic title="庫存總件數" value={items.reduce((sum, item) => sum + Number(item.stock || 0), 0)} prefix={<ShoppingCartOutlined />} /></Card></Col><Col xs={24} md={8}><Card className="stat-card stat-purple" bordered={false}><Statistic title="低庫存品項" value={low.length} prefix={<InboxOutlined />} /></Card></Col></Row><Card className="surface-card" title="新增庫存異動" style={{ marginBottom: 18 }}><Form form={moveForm} layout="inline" onFinish={move}><Form.Item name="product_id" rules={[{ required: true, message: '請選擇商品' }]}><Select style={{ width: 220 }} placeholder="商品" options={items.map((item) => ({ value: item.product_id, label: `${item.product_id} · ${item.name}` }))} /></Form.Item><Form.Item name="move_type" initialValue="入庫"><Select style={{ width: 120 }} options={[{ value: '入庫', label: '入庫' }, { value: '出庫', label: '出庫' }]} /></Form.Item><Form.Item name="quantity" rules={[{ required: true, message: '請輸入數量' }]}><InputNumber min={1} placeholder="數量" /></Form.Item><Form.Item name="ref_no"><Input placeholder="單據編號（選填）" /></Form.Item><Button type="primary" htmlType="submit" icon={<SendOutlined />}>寫入異動</Button></Form></Card><Card className="surface-card" title={<span><InboxOutlined /> 庫存清單</span>}><DataLoading loading={loading}><Table rowKey="product_id" columns={columns} dataSource={items} pagination={{ pageSize: 10 }} /></DataLoading></Card></>
}

export function ProcurementWorkspace() {
  const [orders, setOrders] = useState<any[]>([]); const [suppliers, setSuppliers] = useState<any[]>([]); const [products, setProducts] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [poForm] = Form.useForm()
  const load = async () => { setLoading(true); try { const [po, supplier, inventory] = await Promise.all([api.get('/data/purchase-orders'), api.get('/data/suppliers'), api.get('/data/inventory')]); setOrders(po.data.items || []); setSuppliers(supplier.data.items || []); setProducts(inventory.data.items || []) } catch (e) { message.error(getErrorMessage(e)) } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  const submit = async (values: Record<string, unknown>) => { try { const { data } = await api.post('/data/purchase-orders', values); message.info(data.message || `採購單已送出${data.approval_id ? `，審批單：${data.approval_id}` : ''}`); poForm.resetFields(); await load() } catch (e) { message.error(getErrorMessage(e)) } }
  const columns: TableColumnsType<any> = [
    { title: '採購單', dataIndex: 'po_id' }, { title: '供應商', dataIndex: 'supplier_id' },
    { title: '狀態', dataIndex: 'status', render: (v) => <Tag color={v === '待入庫' ? 'orange' : 'blue'}>{v || '未設定'}</Tag> },
    { title: '金額', dataIndex: 'total_amount', render: (v) => `$${Number(v || 0).toLocaleString()}` },
    { title: '預估延遲', dataIndex: 'estimated_delay_days', render: (v) => Number(v || 0) > 0 ? <Tag color="red">+{v} 天</Tag> : <Tag color="green">正常</Tag> },
  ]
  const supplierColumns: TableColumnsType<any> = [{ title: '供應商', dataIndex: 'name' }, { title: '地區', render: (_, row) => `${row.country || '—'} ${row.region || ''}` }, { title: '風險', dataIndex: 'risk_level', render: (v) => <Tag color={v === '高' ? 'red' : v === '中' ? 'orange' : 'green'}>{v || '未設定'}</Tag> }]
  return <><HeaderBlock eyebrow="ERP / PROCUREMENT" title="採購與供應商" description="建立採購單會走既有 Tool Gateway；需要核准的角色會先進入審批流程。" /><Card className="surface-card" title="送出採購單提案" style={{ marginBottom: 18 }}><Form form={poForm} layout="inline" onFinish={submit}><Form.Item name="po_id" rules={[{ required: true, message: '請輸入採購單號' }]}><Input placeholder="採購單號" /></Form.Item><Form.Item name="supplier_id" rules={[{ required: true, message: '請選供應商' }]}><Select style={{ width: 190 }} placeholder="正式供應商" options={suppliers.map((item) => ({ value: item.supplier_id, label: `${item.supplier_id} · ${item.name}` }))} /></Form.Item><Form.Item name="product_id" rules={[{ required: true, message: '請選品項' }]}><Select style={{ width: 190 }} placeholder="品項" options={products.map((item) => ({ value: item.product_id, label: `${item.product_id} · ${item.name}` }))} /></Form.Item><Form.Item name="qty" rules={[{ required: true, message: '請輸入數量' }]}><InputNumber min={1} placeholder="數量" /></Form.Item><Form.Item name="unit_price" rules={[{ required: true, message: '請輸入單價' }]}><InputNumber min={0} placeholder="單價" /></Form.Item><Button type="primary" htmlType="submit" icon={<SendOutlined />}>送審</Button></Form></Card><Row gutter={[18, 18]}><Col xs={24} xl={15}><Card className="surface-card" title={<span><ShoppingCartOutlined /> 採購單</span>}><DataLoading loading={loading}><Table rowKey="po_id" columns={columns} dataSource={orders} pagination={{ pageSize: 8 }} /></DataLoading></Card></Col><Col xs={24} xl={9}><Card className="surface-card" title={<span><ApartmentOutlined /> 正式供應商</span>}><DataLoading loading={loading}><Table rowKey="supplier_id" columns={supplierColumns} dataSource={suppliers} pagination={{ pageSize: 8 }} /></DataLoading></Card></Col></Row></>
}

export function SalesWorkspace() {
  const [orders, setOrders] = useState<any[]>([]); const [customers, setCustomers] = useState<any[]>([]); const [products, setProducts] = useState<any[]>([]); const [loading, setLoading] = useState(true); const [orderForm] = Form.useForm(); const [statusForm] = Form.useForm()
  const load = async () => { setLoading(true); try { const [order, customer, inventory] = await Promise.all([api.get('/data/orders'), api.get('/data/customers'), api.get('/data/inventory')]); setOrders(order.data.items || []); setCustomers(customer.data.items || []); setProducts(inventory.data.items || []) } catch (e) { message.error(getErrorMessage(e)) } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  const create = async (values: Record<string, unknown>) => { try { const { data } = await api.post('/data/orders', values); message.success(`訂單已建立，目前庫存 ${data.remaining_stock} 件`); orderForm.resetFields(); await load() } catch (e) { message.error(getErrorMessage(e)) } }
  const updateStatus = async (values: { order_id: string; status: string }) => { try { const { data } = await api.post(`/data/orders/${values.order_id}/status`, { status: values.status }); message.success(`訂單已更新，目前庫存 ${data.remaining_stock} 件`); await load() } catch (e) { message.error(getErrorMessage(e)) } }
  const columns: TableColumnsType<any> = [
    { title: '訂單', dataIndex: 'order_id' }, { title: '客戶', dataIndex: 'customer_name', render: (v) => v || '—' }, { title: '商品', dataIndex: 'product_name', render: (v) => v || '—' },
    { title: '數量', dataIndex: 'quantity' }, { title: '狀態', dataIndex: 'status', render: (v) => <Tag color={v === '已取消' ? 'red' : v === '已出貨' ? 'green' : 'blue'}>{v || '未設定'}</Tag> },
    { title: '金額', dataIndex: 'total_amount', render: (v) => `$${Number(v || 0).toLocaleString()}` },
  ]
  return <><HeaderBlock eyebrow="ERP / SALES OPERATIONS" title="銷售訂單與客戶" description="銷售訂單會使用原子庫存扣減；取消或狀態回復會自動補回庫存。" /><Row gutter={[18, 18]}><Col xs={24} xl={14}><Card className="surface-card" title="建立銷售訂單"><Form form={orderForm} layout="inline" onFinish={create}><Form.Item name="order_id" rules={[{ required: true, message: '請輸入訂單號' }]}><Input placeholder="訂單編號" /></Form.Item><Form.Item name="customer_id"><Select allowClear style={{ width: 170 }} placeholder="客戶" options={customers.map((item) => ({ value: item.customer_id, label: `${item.customer_id} · ${item.name}` }))} /></Form.Item><Form.Item name="product_id" rules={[{ required: true, message: '請選商品' }]}><Select style={{ width: 170 }} placeholder="商品" options={products.map((item) => ({ value: item.product_id, label: `${item.product_id} · ${item.name}` }))} /></Form.Item><Form.Item name="quantity" rules={[{ required: true, message: '請輸入數量' }]}><InputNumber min={1} placeholder="數量" /></Form.Item><Form.Item name="status" initialValue="處理中"><Select style={{ width: 110 }} options={['處理中', '已出貨', '已取消'].map((value) => ({ value, label: value }))} /></Form.Item><Button type="primary" htmlType="submit">建立</Button></Form></Card></Col><Col xs={24} xl={10}><Card className="surface-card" title="更新訂單狀態"><Form form={statusForm} layout="inline" onFinish={updateStatus}><Form.Item name="order_id" rules={[{ required: true, message: '請選訂單' }]}><Select style={{ width: 190 }} placeholder="訂單" options={orders.map((item) => ({ value: item.order_id, label: `${item.order_id} (${item.status})` }))} /></Form.Item><Form.Item name="status" rules={[{ required: true, message: '請選狀態' }]}><Select style={{ width: 110 }} placeholder="新狀態" options={['處理中', '已出貨', '已取消'].map((value) => ({ value, label: value }))} /></Form.Item><Button htmlType="submit">更新</Button></Form></Card></Col></Row><Row gutter={[16, 16]} className="stat-row"><Col xs={24} md={8}><Card className="stat-card stat-blue" bordered={false}><Statistic title="訂單總數" value={orders.length} prefix={<ShoppingCartOutlined />} /></Card></Col><Col xs={24} md={8}><Card className="stat-card stat-orange" bordered={false}><Statistic title="客戶總數" value={customers.length} prefix={<UserOutlined />} /></Card></Col><Col xs={24} md={8}><Card className="stat-card stat-purple" bordered={false}><Statistic title="待處理訂單" value={orders.filter((item) => !['已出貨', '已取消'].includes(item.status)).length} prefix={<InboxOutlined />} /></Card></Col></Row><Card className="surface-card" title={<span><ShoppingCartOutlined /> 銷售訂單</span>}><DataLoading loading={loading}><Table rowKey="order_id" columns={columns} dataSource={orders} pagination={{ pageSize: 10 }} /></DataLoading></Card></>
}

export function AssistantWorkspace({ canRun }: { canRun: boolean }) {
  const [question, setQuestion] = useState('哪些供應鏈風險需要優先處理？'); const [answer, setAnswer] = useState(''); const [loading, setLoading] = useState(false)
  const run = async () => { setLoading(true); try { setAnswer((await api.post('/copilot/chat', { message: question })).data.answer) } catch (e) { setAnswer(getErrorMessage(e)) } finally { setLoading(false) } }
  return <><HeaderBlock eyebrow="AI / COPILOT" title="AI 供應鏈助理" description="用自然語言詢問風險、ERP 證據與下一步行動；回答會沿用目前的權限與模型設定。" /><Card className="scenario-card" bordered={false}><div className="scenario-heading"><div className="scenario-icon"><RobotOutlined /></div><div><Title level={4}>問問你的供應鏈</Title><Text type="secondary">目前仍使用虛擬資料，未設定模型金鑰時會顯示清楚的不可用狀態。</Text></div></div><Input.TextArea value={question} onChange={(event) => setQuestion(event.target.value)} autoSize={{ minRows: 4, maxRows: 8 }} /><div className="scenario-actions"><Text type="secondary">AI 分析權限：{canRun ? '已開啟' : '未開啟'}</Text><Button type="primary" onClick={run} loading={loading} disabled={!canRun || question.trim().length < 2} icon={<RobotOutlined />}>送出問題</Button></div>{answer && <Alert className="scenario-answer" message="分析結果" description={<pre>{answer}</pre>} type="success" showIcon />}</Card></>
}

export function SustainabilityWorkspace() {
  const [carbon, setCarbon] = useState<any>({ by_scope: [], by_product: [] }); const [map, setMap] = useState<any>({ suppliers: [], heatmap: [], events: [] }); const [targets, setTargets] = useState<any[]>([]); const [period, setPeriod] = useState(''); const [loading, setLoading] = useState(true)
  const load = async () => { setLoading(true); try { const [carbonRes, mapRes, targetRes] = await Promise.all([api.get('/data/esg/carbon', { params: { year_month: period } }), api.get('/data/supply-chain/map'), api.get('/data/esg/targets')]); setCarbon(carbonRes.data); setMap(mapRes.data); setTargets(targetRes.data.items || []) } catch (e) { message.error(getErrorMessage(e)) } finally { setLoading(false) } }
  useEffect(() => { void load() }, [])
  return <><HeaderBlock eyebrow="ESG / SUPPLY CHAIN" title="碳排與供應鏈地圖" description="把碳排係數、供應商據點與風險熱點放在同一個決策頁，支援後續 ESG 與替代供應分析。" /><Card className="surface-card" title="碳排期間"><Space><Input value={period} onChange={(e) => setPeriod(e.target.value)} placeholder="YYYY-MM（留空為全部）" /><Button onClick={() => void load()} loading={loading}>重新計算</Button></Space></Card><Row gutter={[18, 18]} style={{ marginTop: 18 }}><Col xs={24} xl={12}><Card className="surface-card" title="依 Scope 碳排"><Table loading={loading} rowKey="scope" pagination={false} dataSource={carbon.by_scope} columns={[{ title: 'Scope', dataIndex: 'scope', render: (v: any) => `Scope ${v}` }, { title: 'kg CO₂e', dataIndex: 'carbon_kg', render: (v: any) => Number(v || 0).toLocaleString() }]} /></Card></Col><Col xs={24} xl={12}><Card className="surface-card" title="產品碳足跡"><Table loading={loading} rowKey="product_id" pagination={{ pageSize: 6 }} dataSource={carbon.by_product} columns={[{ title: '商品', dataIndex: 'name' }, { title: '數量', dataIndex: 'quantity' }, { title: 'kg CO₂e', dataIndex: 'carbon_kg', render: (v: any) => Number(v || 0).toLocaleString() }]} /></Card></Col></Row><Row gutter={[18, 18]} style={{ marginTop: 0 }}><Col xs={24} xl={14}><Card className="surface-card" title="供應商據點與風險"><Table loading={loading} rowKey="supplier_id" pagination={{ pageSize: 8 }} dataSource={map.suppliers} columns={[{ title: '供應商', dataIndex: 'name' }, { title: '國家／地區', render: (_: unknown, row: any) => `${row.country || '—'} ${row.region || ''}` }, { title: '風險', dataIndex: 'risk_level', render: (v: any) => <Tag color={v === '高' ? 'red' : v === '中' ? 'orange' : 'green'}>{v || '未設定'}</Tag> }, { title: '座標', render: (_: unknown, row: any) => row.latitude && row.longitude ? `${Number(row.latitude).toFixed(3)}, ${Number(row.longitude).toFixed(3)}` : '—' }]} /></Card></Col><Col xs={24} xl={10}><Card className="surface-card" title="風險熱點"><Table loading={loading} rowKey="region_key" pagination={false} dataSource={map.heatmap} columns={[{ title: '地區', dataIndex: 'display_name' }, { title: '風險', dataIndex: 'risk_pct', render: (v: any) => <Tag color={Number(v) >= 70 ? 'red' : Number(v) >= 40 ? 'orange' : 'green'}>{Math.round(Number(v || 0))}%</Tag> }]} /></Card><Card className="surface-card" title="ESG 目標" style={{ marginTop: 18 }}><Table loading={loading} rowKey="id" pagination={false} dataSource={targets} columns={[{ title: '年度', dataIndex: 'target_year' }, { title: 'Scope', dataIndex: 'scope' }, { title: '目標 kg', dataIndex: 'target_kg_co2', render: (v: any) => Number(v || 0).toLocaleString() }]} /></Card></Col></Row></>
}
